import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm, FormProvider } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { useAppSelector, useAppDispatch } from '@/store';
import { setActiveTab, resetOnboardingState, addTimelineEvent } from '@/store/features/employeeOnboardingSlice';

import { employeeOnboardingSchema } from './schemas/employee.schema';
import { type EmployeeFormData } from './types/employee.types';
import { useEmployeeDraft } from './hooks/useEmployeeDraft';
import { useEmployeeAutoSave } from './hooks/useEmployeeAutoSave';
import { useEmployeeValidation } from './hooks/useEmployeeValidation';
import { employeeService } from './services/employee.service';

import { AddEmployeeHeader } from './components/header/AddEmployeeHeader';
import { TabNavigation, TABS_LIST } from './components/tabs/TabNavigation';
import { notify } from '@/services/notificationService';

// Lazy-rendering tab sections
import { PersonalDetailsSection } from './components/sections/PersonalDetailsSection';
import { EmploymentDetailsSection } from './components/sections/EmploymentDetailsSection';
import { ContactAddressSection } from './components/sections/ContactAddressSection';
import { FamilyInformationSection } from './components/sections/FamilyInformationSection';
import { EducationSection } from './components/sections/EducationSection';
import { WorkExperienceSection } from './components/sections/WorkExperienceSection';
import { SkillsCertificationsSection } from './components/sections/SkillsCertificationsSection';
import { DocumentsKycSection } from './components/sections/DocumentsKycSection';
import { BankPayrollSection } from './components/sections/BankPayrollSection';
import { MedicalInformationSection } from './components/sections/MedicalInformationSection';
import { SystemAccessSection } from './components/sections/SystemAccessSection';
import { SalaryStructureSection } from './components/sections/SalaryStructureSection';
import { StatutorySection } from './components/sections/StatutorySection';
import { AssetsJoiningKitSection } from './components/sections/AssetsJoiningKitSection';
import { NotesAttachmentsSection } from './components/sections/NotesAttachmentsSection';
import { ReviewSubmitSection } from './components/review/ReviewSubmitSection';

// Dialog/Confirmation components from shadcn
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { ArrowLeft, ArrowRight, ShieldCheck, Check } from 'lucide-react';

const INITIAL_FORM_VALUES: Partial<EmployeeFormData> = {
  employeeId: '',
  firstName: '',
  lastName: '',
  fullName: '',
  dob: '',
  gender: '',
  maritalStatus: '',
  nationality: 'Indian',
  department: '',
  designation: '',
  joiningDate: new Date().toISOString().split('T')[0],
  reportingManager: '',
  officialEmail: '',
  confirmationDate: '',
  workMode: 'Onsite',
  employeeType: 'Full-time',
  isRehire: false,
  mobile: '',
  personalEmail: '',
  presentAddress: { street: '', city: '', state: '', district: '', pin: '' },
  sameAsPresent: false,
  permanentAddress: { street: '', city: '', state: '', district: '', pin: '' },
  emergencyContactName: '',
  emergencyContactRelation: '',
  emergencyContactPhone: '',
  fatherName: '',
  motherName: '',
  dependents: [],
  education: [],
  experience: [],
  skills: [],
  certifications: [],
  panNumber: '',
  aadhaarNumber: '',
  passportNumber: '',
  panFileUrl: '',
  aadhaarFileUrl: '',
  passportFileUrl: '',
  bankName: '',
  accountHolderName: '',
  accountNumber: '',
  ifscCode: '',
  branchName: '',
  accountType: 'Savings',
  bloodGroup: 'B+',
  insuranceOpted: false,
  username: '',
  password: '',
  role: 'Employee',
  enable2FA: false,
  basicSalary: 0,
  hra: 0,
  lta: 0,
  specialAllowance: 0,
  employerPf: 0,
  employeePf: 0,
  professionalTax: 0,
  otherDeductions: 0,
  grossSalary: 0,
  netSalary: 0,
  pfEnrolled: true,
  esiEnrolled: false,
  ptEnrolled: true,
  statutoryDeductionsEnrolled: true,
  laptopAssigned: false,
  joiningKitIssued: false,
  kitItems: [],
  notes: '',
  attachments: []
};

export default function AddEmployeePage() {
  const navigate = useNavigate();
  const dispatch = useAppDispatch();
  
  const activeTab = useAppSelector((state) => state.employeeOnboarding.activeTab);
  const tabCompletions = useAppSelector((state) => state.employeeOnboarding.tabCompletions);
  
  const [autoGeneratedId, setAutoGeneratedId] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitConfirmOpen, setSubmitConfirmOpen] = useState(false);

  // Initialize Form
  const methods = useForm<any>({
    resolver: zodResolver(employeeOnboardingSchema),
    defaultValues: INITIAL_FORM_VALUES,
    mode: 'onChange'
  });

  const { handleSubmit, reset, watch, trigger, getValues, formState: { errors, isDirty } } = methods;

  // 1. Load Auto-generated ID on mount
  useEffect(() => {
    const fetchId = async () => {
      try {
        const nextId = await employeeService.generateEmployeeId();
        setAutoGeneratedId(nextId);
        setValue('employeeId', nextId, { shouldValidate: true });
        dispatch(addTimelineEvent({ message: `Assigned auto-generated ID: ${nextId}`, type: 'info' }));
      } catch (err) {
        console.error('Failed to generate employee ID', err);
      }
    };
    fetchId();
  }, [dispatch]);

  const { setValue } = methods;

  // Custom Hooks Setup
  const { restoreDraft, saveDraft, hasDraftInStorage } = useEmployeeDraft(reset);
  useEmployeeAutoSave(watch, isDirty);
  const { validateTab, getCompletionPercentage } = useEmployeeValidation(trigger, errors);

  const completionPercentage = getCompletionPercentage(tabCompletions);

  // Tab Indexing for Next/Back buttons
  const currentTabIdx = TABS_LIST.findIndex((tab) => tab.name === activeTab);

  const handleNextTab = async () => {
    // 1. Validate active tab fields first
    const isValid = await validateTab(activeTab);
    if (!isValid) {
      notify.error('Section Incomplete', 'Please fill out all required fields in this section before continuing.');
      return;
    }

    // 2. Advance to next tab
    if (currentTabIdx < TABS_LIST.length - 1) {
      const nextTab = TABS_LIST[currentTabIdx + 1].name;
      dispatch(setActiveTab(nextTab));
      
      // Scroll content area back to top
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handleBackTab = () => {
    if (currentTabIdx > 0) {
      const prevTab = TABS_LIST[currentTabIdx - 1].name;
      dispatch(setActiveTab(prevTab));
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  // Save Draft Manually
  const handleSaveDraftManual = () => {
    const vals = getValues();
    saveDraft(vals);
  };

  // Submit flow
  const handleCompleteOnboardingClick = () => {
    setSubmitConfirmOpen(true);
  };

  const handleFinalSubmit = async () => {
    setSubmitConfirmOpen(false);
    setIsSubmitting(true);
    const data = getValues();
    
    dispatch(addTimelineEvent({ message: 'Submitting finalized candidate dossier.', type: 'info' }));
    
    try {
      const res = await employeeService.submitEmployee(data);
      if (res.success) {
        notify.success('Onboarding Successful', 'Employee record enrolled successfully! Redirecting...');
        dispatch(addTimelineEvent({ message: 'Central Ledger Lock secured.', type: 'success' }));
        
        // Clear drafts & local storage
        localStorage.removeItem('erp_employee_onboarding_draft');
        dispatch(resetOnboardingState());
        
        setTimeout(() => {
          setIsSubmitting(false);
          navigate('/hrms');
        }, 1500);
      }
    } catch (err) {
      setIsSubmitting(false);
      notify.error('Submission Failed', 'Failed to synchronize with central HR database.');
    }
  };

  // Lazy Render Tab Picker Switch
  const renderTabContent = () => {
    switch (activeTab) {
      case 'Personal Information':
        return <PersonalDetailsSection />;
      case 'Employment Details':
        return <EmploymentDetailsSection />;
      case 'Contact & Address':
        return <ContactAddressSection />;
      case 'Family Information':
        return <FamilyInformationSection />;
      case 'Education':
        return <EducationSection />;
      case 'Work Experience':
        return <WorkExperienceSection />;
      case 'Skills & Certifications':
        return <SkillsCertificationsSection />;
      case 'Documents & KYC':
        return <DocumentsKycSection />;
      case 'Bank & Payroll':
        return <BankPayrollSection />;
      case 'Medical Information':
        return <MedicalInformationSection />;
      case 'System Access':
        return <SystemAccessSection />;
      case 'Salary Structure':
        return <SalaryStructureSection />;
      case 'PF / ESI / Statutory':
        return <StatutorySection />;
      case 'Assets & Joining Kit':
        return <AssetsJoiningKitSection />;
      case 'Notes & Attachments':
        return <NotesAttachmentsSection />;
      case 'Review & Submit':
        return (
          <ReviewSubmitSection
            onSubmit={handleCompleteOnboardingClick}
            isSubmitting={isSubmitting}
            completionPercentage={completionPercentage}
          />
        );
      default:
        return <PersonalDetailsSection />;
    }
  };

  return (
    <FormProvider {...methods}>
      <div className="flex flex-col gap-6 p-4 md:p-8 max-w-7xl mx-auto animate-in fade-in duration-500 pb-20">
        
        {/* Sticky page header */}
        <AddEmployeeHeader
          onSaveDraft={handleSaveDraftManual}
          onSubmit={handleCompleteOnboardingClick}
          onRestoreDraft={restoreDraft}
          hasDraft={hasDraftInStorage}
          isSubmitting={isSubmitting}
          completionPercentage={completionPercentage}
          employeeId={autoGeneratedId}
        />

        {/* Form Container Grid Layout */}
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 items-start mt-2">
          {/* Left panel: Vertical Roadmap tab list */}
          <div className="lg:col-span-1 lg:sticky lg:top-40 z-30">
            <TabNavigation onTabChange={() => {}} errors={errors} />
          </div>

          {/* Right panel: Active Card container contents */}
          <div className="lg:col-span-3 space-y-6">
            <div className="min-h-[500px]">
              {renderTabContent()}
            </div>

            {/* Bottom Form Navigation controls */}
            <div className="flex items-center justify-between border-t pt-4 mt-8 bg-background/50 p-4 rounded-2xl border">
              <Button
                type="button"
                variant="outline"
                onClick={handleBackTab}
                disabled={currentTabIdx === 0}
                className="h-10 rounded-xl px-5 border-muted bg-background hover:bg-muted text-xs font-bold gap-1.5"
              >
                <ArrowLeft className="h-4 w-4" />
                Previous Step
              </Button>

              {activeTab !== 'Review & Submit' ? (
                <Button
                  type="button"
                  onClick={handleNextTab}
                  className="h-10 rounded-xl px-6 bg-primary text-primary-foreground font-bold text-xs gap-1.5 shadow-sm hover:bg-primary/90"
                >
                  Save & Continue
                  <ArrowRight className="h-4 w-4" />
                </Button>
              ) : (
                <Button
                  type="button"
                  onClick={handleCompleteOnboardingClick}
                  disabled={isSubmitting || completionPercentage < 100}
                  className="h-10 rounded-xl px-6 bg-emerald-600 hover:bg-emerald-600/90 text-white font-bold text-xs gap-1.5 shadow-sm"
                >
                  <ShieldCheck className="h-4 w-4" />
                  Finalize & Sync
                </Button>
              )}
            </div>
          </div>
        </div>

        {/* Central Ledger Double Confirmation Dialog */}
        <Dialog open={submitConfirmOpen} onOpenChange={setSubmitConfirmOpen}>
          <DialogContent className="rounded-3xl max-w-md p-6 bg-background border">
            <DialogHeader className="flex flex-col items-center text-center gap-3">
              <div className="h-12 w-12 rounded-full bg-emerald-500/10 text-emerald-500 border border-emerald-500/30 flex items-center justify-center">
                <ShieldCheck className="h-6 w-6" />
              </div>
              <div>
                <DialogTitle className="text-lg font-bold text-foreground">Double Confirmation Check</DialogTitle>
                <DialogDescription className="text-xs text-muted-foreground mt-1">
                  Enrolling this candidate commits their files to the central database, locking statutory allowances and generating gate RFID tags.
                </DialogDescription>
              </div>
            </DialogHeader>

            <div className="bg-muted/30 border border-dashed p-4 rounded-2xl space-y-2 mt-4 text-xs font-semibold leading-relaxed text-muted-foreground">
              <div className="flex items-start gap-2">
                <Check className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Central database locks the assigned ID <span className="text-foreground font-extrabold">{autoGeneratedId}</span>.</span>
              </div>
              <div className="flex items-start gap-2">
                <Check className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Sends automated corporate welcome credentials invite.</span>
              </div>
              <div className="flex items-start gap-2">
                <Check className="h-4 w-4 text-emerald-500 shrink-0 mt-0.5" />
                <span>Processes direct bank salary structures setup.</span>
              </div>
            </div>

            <DialogFooter className="grid grid-cols-2 gap-3 mt-6">
              <Button
                type="button"
                variant="outline"
                onClick={() => setSubmitConfirmOpen(false)}
                className="h-10 rounded-xl border-muted text-xs font-bold bg-background hover:bg-muted"
              >
                Cancel Review
              </Button>
              <Button
                type="button"
                onClick={handleFinalSubmit}
                className="h-10 rounded-xl bg-emerald-600 hover:bg-emerald-600/90 text-white text-xs font-bold"
              >
                Approve & Sync
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
    </FormProvider>
  );
}
export { AddEmployeePage };
