import React, { useState } from 'react';
import { Building2, FileCheck2, RotateCcw, Save } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { DataTable, PageHeader, StatCard, formatINR } from '@/tenant/components/TenantUI';
import { HrStatusBadge } from '@/tenant/hr/HrStatusBadge';
import { useHrData } from '@/tenant/hr/HrDataProvider';
import { getDepartmentHeadcount, getMonthlyPayrollCost } from '@/tenant/hr/hrDemoService';

export const DepartmentsPage: React.FC = () => {
  const hr = useHrData();
  return <div><PageHeader title="Departments" description="Department ownership, location, headcount, and annual operating budget." /><DataTable headers={['Department', 'Head', 'Location', 'Employees', 'Annual budget']}>{hr.departments.map((department) => <tr key={department.id}><td className="px-4 py-3"><div className="flex items-center gap-2 font-medium text-slate-950"><Building2 className="h-4 w-4 text-indigo-600" />{department.name}</div></td><td className="px-4 py-3 text-slate-600">{department.head}</td><td className="px-4 py-3 text-slate-600">{department.location}</td><td className="px-4 py-3 text-slate-600">{hr.employees.filter((employee) => employee.department === department.name).length}</td><td className="px-4 py-3 font-medium text-slate-950">{formatINR(department.budget)}</td></tr>)}</DataTable></div>;
};

export const HrDocumentsPage: React.FC = () => {
  const hr = useHrData();
  return <div><PageHeader title="Employee Documents" description="Identity, contract, banking, and certification records with verification status." /><section className="mb-5 grid gap-4 sm:grid-cols-3"><StatCard label="Documents" value={String(hr.documents.length)} icon={<FileCheck2 className="h-4 w-4" />} /><StatCard label="Verified" value={String(hr.documents.filter((document) => document.status === 'Verified').length)} /><StatCard label="Pending" value={String(hr.documents.filter((document) => document.status === 'Pending').length)} /></section><DataTable headers={['Employee', 'Document type', 'File name', 'Expiry date', 'Status']}>{hr.documents.map((document) => <tr key={document.id}><td className="px-4 py-3 font-medium text-slate-950">{document.employeeName}</td><td className="px-4 py-3 text-slate-600">{document.documentType}</td><td className="px-4 py-3 font-medium text-indigo-700">{document.fileName}</td><td className="px-4 py-3 text-slate-600">{document.expiryDate || 'Not applicable'}</td><td className="px-4 py-3"><HrStatusBadge status={document.status} /></td></tr>)}</DataTable></div>;
};

export const HrReportsPage: React.FC = () => {
  const hr = useHrData();
  const headcount = getDepartmentHeadcount(hr);
  const totalHours = hr.attendance.reduce((sum, entry) => sum + entry.workHours, 0);
  const approvedLeave = hr.leaveRequests.filter((leave) => leave.status === 'Approved').reduce((sum, leave) => sum + leave.days, 0);
  return <div><PageHeader title="HR Reports" description="Attendance summary, leave report, salary register, overtime, and compliance views." /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Attendance hours" value={totalHours.toFixed(1)} hint="June recorded hours" /><StatCard label="Approved leave days" value={String(approvedLeave)} /><StatCard label="Salary register" value={formatINR(getMonthlyPayrollCost(hr))} hint="Current monthly net" /><StatCard label="Active departments" value={String(headcount.filter((item) => item.count > 0).length)} /></section><section className="mt-5 grid gap-5 xl:grid-cols-2"><ReportPanel title="Attendance summary">{hr.employees.map((employee) => { const entries = hr.attendance.filter((entry) => entry.employeeId === employee.id); const present = entries.filter((entry) => ['Present', 'Late', 'Half Day'].includes(entry.status)).length; return <ReportBar key={employee.id} label={employee.name} value={`${present}/${entries.length}`} percent={(present / entries.length) * 100} tone="bg-emerald-600" />; })}</ReportPanel><ReportPanel title="Leave report">{['Casual Leave', 'Sick Leave', 'Earned Leave', 'Comp Off'].map((type) => { const count = hr.leaveRequests.filter((leave) => leave.leaveType === type).reduce((sum, leave) => sum + leave.days, 0); return <ReportBar key={type} label={type} value={`${count} days`} percent={(count / Math.max(...hr.leaveRequests.map((leave) => leave.days), 1)) * 100} tone="bg-violet-600" />; })}</ReportPanel></section><section className="mt-5 grid gap-5 xl:grid-cols-2"><ReportPanel title="Salary register">{headcount.map((department) => { const total = hr.employees.filter((employee) => employee.department === department.name).reduce((sum, employee) => sum + employee.salary.basic + employee.salary.allowances - employee.salary.deductions - employee.salary.pf - employee.salary.esi, 0); return <ReportBar key={department.name} label={department.name} value={formatINR(total)} percent={(total / getMonthlyPayrollCost(hr)) * 100} tone="bg-cyan-600" />; })}</ReportPanel><div className="grid gap-4 sm:grid-cols-2"><Placeholder title="Overtime report" description="Placeholder for shift and overtime analysis." /><Placeholder title="Compliance report" description="Placeholder for PF, ESI, and statutory reporting." /></div></section></div>;
};

export const HrSettingsPage: React.FC = () => {
  const hr = useHrData();
  const [saved, setSaved] = useState(false);
  const [settings, setSettings] = useState({ geoAttendance: false, lateAlerts: true, autoLeaveBalance: true, payrollApproval: true, documentExpiry: true });
  return <div><PageHeader title="HR Settings" description="Attendance, leave, payroll, and employee document defaults." /><div className="grid gap-5 xl:grid-cols-2"><SettingsPanel title="Attendance and leave"><SettingRow label="Location-based attendance" description="Capture the employee work location when marking attendance." checked={settings.geoAttendance} onChange={(checked) => setSettings({ ...settings, geoAttendance: checked })} /><SettingRow label="Late arrival alerts" description="Flag check-ins after the attendance grace period." checked={settings.lateAlerts} onChange={(checked) => setSettings({ ...settings, lateAlerts: checked })} /><SettingRow label="Automatic leave balances" description="Recalculate balances after leave approval." checked={settings.autoLeaveBalance} onChange={(checked) => setSettings({ ...settings, autoLeaveBalance: checked })} /></SettingsPanel><SettingsPanel title="Payroll and documents"><SettingRow label="Payroll approval step" description="Require approval before salary slips can be paid." checked={settings.payrollApproval} onChange={(checked) => setSettings({ ...settings, payrollApproval: checked })} /><SettingRow label="Document expiry alerts" description="Notify HR before employee documents expire." checked={settings.documentExpiry} onChange={(checked) => setSettings({ ...settings, documentExpiry: checked })} /></SettingsPanel></div><div className="mt-5 flex flex-wrap items-center gap-3"><Button onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1800); }}><Save className="h-4 w-4" />Save settings</Button><Button variant="outline" onClick={hr.resetHrData}><RotateCcw className="h-4 w-4" />Reset demo data</Button>{saved && <span className="text-sm font-medium text-emerald-700">Settings saved</span>}</div></div>;
};

const ReportPanel: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <div className="rounded-md border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-semibold text-slate-950">{title}</h2><div className="mt-4 space-y-3">{children}</div></div>;
const ReportBar: React.FC<{ label: string; value: string; percent: number; tone: string }> = ({ label, value, percent, tone }) => <div><div className="flex justify-between gap-3 text-sm"><span className="truncate font-medium text-slate-700">{label}</span><span className="shrink-0 text-slate-500">{value}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className={`h-2 rounded-full ${tone}`} style={{ width: `${Math.max(3, Math.min(100, percent))}%` }} /></div></div>;
const Placeholder: React.FC<{ title: string; description: string }> = ({ title, description }) => <div className="rounded-md border border-dashed border-slate-300 bg-white p-6 text-center"><h2 className="font-semibold text-slate-800">{title}</h2><p className="mt-1 text-sm text-slate-500">{description}</p></div>;
const SettingsPanel: React.FC<{ title: string; children: React.ReactNode }> = ({ title, children }) => <section className="rounded-md border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">{title}</h2><div className="mt-4 space-y-3">{children}</div></section>;
const SettingRow: React.FC<{ label: string; description: string; checked: boolean; onChange: (checked: boolean) => void }> = ({ label, description, checked, onChange }) => <div className="flex items-start justify-between gap-4 rounded-sm border border-slate-200 p-3"><div><p className="text-sm font-medium text-slate-800">{label}</p><p className="mt-0.5 text-xs text-slate-500">{description}</p></div><Switch checked={checked} onCheckedChange={onChange} /></div>;
