import React, { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { HR_DEPARTMENTS, HR_TEAM, HR_WORKING_DAYS } from '@/tenant/hr/hrDemoService';
import type { Branch, BranchDraft, DesignationDraft, HolidayDraft, LeavePolicyDraft, ShiftGroupDraft } from '@/tenant/hr/types';

const selectClass = 'flex h-10 w-full rounded-sm border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100';
const Field: React.FC<{ label: string; children: React.ReactNode; className?: string }> = ({ label, children, className }) => <Label className={`block ${className || ''}`}><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}</span>{children}</Label>;

const WorkingDaysPicker: React.FC<{ value: string[]; onChange: (days: string[]) => void }> = ({ value, onChange }) => (
  <div className="flex flex-wrap gap-2">
    {HR_WORKING_DAYS.map((day) => (
      <Label key={day} className="flex items-center gap-2 rounded-sm border border-slate-200 bg-slate-50 px-2.5 py-2 text-xs font-medium text-slate-700">
        <Checkbox checked={value.includes(day)} onCheckedChange={(checked) => onChange(checked ? [...value, day] : value.filter((item) => item !== day))} />
        {day}
      </Label>
    ))}
  </div>
);

export const BranchForm: React.FC<{ onSubmit: (draft: BranchDraft) => void }> = ({ onSubmit }) => {
  const [draft, setDraft] = useState<BranchDraft>({ name: '', code: '', city: 'Bhubaneswar', state: 'Odisha', address: '', admin: 'Priya Mishra', workingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], holidayCalendar: 'Odisha Corporate Calendar', status: 'Active' });
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(draft); }}><Field label="Branch name"><Input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Branch code"><Input required value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value })} /></Field><Field label="City"><Input required value={draft.city} onChange={(event) => setDraft({ ...draft, city: event.target.value })} /></Field><Field label="State"><Input required value={draft.state} onChange={(event) => setDraft({ ...draft, state: event.target.value })} /></Field><Field label="Branch admin"><select className={selectClass} value={draft.admin} onChange={(event) => setDraft({ ...draft, admin: event.target.value })}>{HR_TEAM.map((person) => <option key={person}>{person}</option>)}</select></Field><Field label="Status"><select className={selectClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as BranchDraft['status'] })}>{['Active', 'Draft', 'Inactive'].map((status) => <option key={status}>{status}</option>)}</select></Field><Field label="Working days" className="sm:col-span-2"><WorkingDaysPicker value={draft.workingDays} onChange={(workingDays) => setDraft({ ...draft, workingDays })} /></Field><Field label="Holiday calendar" className="sm:col-span-2"><Input value={draft.holidayCalendar} onChange={(event) => setDraft({ ...draft, holidayCalendar: event.target.value })} /></Field><Field label="Address" className="sm:col-span-2"><Textarea required value={draft.address} onChange={(event) => setDraft({ ...draft, address: event.target.value })} /></Field><div className="flex justify-end sm:col-span-2"><Button type="submit">Add branch</Button></div></form>;
};

export const DesignationForm: React.FC<{ onSubmit: (draft: DesignationDraft) => void }> = ({ onSubmit }) => {
  const [draft, setDraft] = useState<DesignationDraft>({ title: '', department: 'Engineering', level: 'Associate', employmentType: 'Full Time', status: 'Active' });
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(draft); }}><Field label="Designation title"><Input required value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></Field><Field label="Department"><select className={selectClass} value={draft.department} onChange={(event) => setDraft({ ...draft, department: event.target.value })}>{HR_DEPARTMENTS.map((department) => <option key={department}>{department}</option>)}</select></Field><Field label="Level"><select className={selectClass} value={draft.level} onChange={(event) => setDraft({ ...draft, level: event.target.value })}>{['Associate', 'Senior Associate', 'Manager', 'Senior Manager', 'Leadership'].map((level) => <option key={level}>{level}</option>)}</select></Field><Field label="Employment type"><select className={selectClass} value={draft.employmentType} onChange={(event) => setDraft({ ...draft, employmentType: event.target.value })}>{['Full Time', 'Part Time', 'Contract', 'Intern'].map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Status"><select className={selectClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as DesignationDraft['status'] })}>{['Active', 'Draft', 'Inactive'].map((status) => <option key={status}>{status}</option>)}</select></Field><div className="flex justify-end sm:col-span-2"><Button type="submit">Add designation</Button></div></form>;
};

export const LeavePolicyForm: React.FC<{ onSubmit: (draft: LeavePolicyDraft) => void }> = ({ onSubmit }) => {
  const [draft, setDraft] = useState<LeavePolicyDraft>({ code: '', name: '', paid: true, annualAllowance: 12, carryForward: false, maxCarryForward: 0, encashment: false, expiryRule: 'Expires at financial year end', approvalChain: 'Manager -> HR Admin', status: 'Active' });
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(draft); }}><Field label="Leave code"><Input required value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value.toUpperCase() })} /></Field><Field label="Leave name"><Input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Annual allowance"><Input type="number" min="0" value={draft.annualAllowance} onChange={(event) => setDraft({ ...draft, annualAllowance: Number(event.target.value) })} /></Field><Field label="Max carry forward"><Input type="number" min="0" value={draft.maxCarryForward} onChange={(event) => setDraft({ ...draft, maxCarryForward: Number(event.target.value) })} /></Field><Field label="Approval chain"><Input value={draft.approvalChain} onChange={(event) => setDraft({ ...draft, approvalChain: event.target.value })} /></Field><Field label="Status"><select className={selectClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as LeavePolicyDraft['status'] })}>{['Active', 'Draft', 'Inactive'].map((status) => <option key={status}>{status}</option>)}</select></Field><Field label="Expiry rule" className="sm:col-span-2"><Textarea value={draft.expiryRule} onChange={(event) => setDraft({ ...draft, expiryRule: event.target.value })} /></Field><div className="grid gap-2 sm:col-span-2 sm:grid-cols-3"><CheckRow label="Paid leave" checked={draft.paid} onChange={(paid) => setDraft({ ...draft, paid })} /><CheckRow label="Carry forward" checked={draft.carryForward} onChange={(carryForward) => setDraft({ ...draft, carryForward })} /><CheckRow label="Encashment" checked={draft.encashment} onChange={(encashment) => setDraft({ ...draft, encashment })} /></div><div className="flex justify-end sm:col-span-2"><Button type="submit">Add leave policy</Button></div></form>;
};

export const HolidayForm: React.FC<{ branches: Branch[]; onSubmit: (draft: HolidayDraft) => void }> = ({ branches, onSubmit }) => {
  const [draft, setDraft] = useState<HolidayDraft>({ name: '', date: '2026-08-15', branchId: 'all', type: 'Public Holiday', status: 'Active' });
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(draft); }}><Field label="Holiday name"><Input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Date"><Input type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} /></Field><Field label="Branch"><select className={selectClass} value={draft.branchId} onChange={(event) => setDraft({ ...draft, branchId: event.target.value })}><option value="all">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field><Field label="Type"><select className={selectClass} value={draft.type} onChange={(event) => setDraft({ ...draft, type: event.target.value as HolidayDraft['type'] })}>{['Public Holiday', 'Optional Holiday', 'Branch Holiday', 'Special Working Day'].map((type) => <option key={type}>{type}</option>)}</select></Field><Field label="Status"><select className={selectClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as HolidayDraft['status'] })}>{['Active', 'Draft', 'Inactive'].map((status) => <option key={status}>{status}</option>)}</select></Field><div className="flex justify-end sm:col-span-2"><Button type="submit">Add holiday</Button></div></form>;
};

export const ShiftGroupForm: React.FC<{ branches: Branch[]; onSubmit: (draft: ShiftGroupDraft) => void }> = ({ branches, onSubmit }) => {
  const [draft, setDraft] = useState<ShiftGroupDraft>({ name: '', branchId: branches[0]?.id || '', startTime: '09:30', endTime: '18:00', graceMinutes: 15, overtimeEligible: false, workingDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], status: 'Active' });
  return <form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(draft); }}><Field label="Shift name"><Input required value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></Field><Field label="Branch"><select className={selectClass} value={draft.branchId} onChange={(event) => setDraft({ ...draft, branchId: event.target.value })}>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field><Field label="Start time"><Input type="time" value={draft.startTime} onChange={(event) => setDraft({ ...draft, startTime: event.target.value })} /></Field><Field label="End time"><Input type="time" value={draft.endTime} onChange={(event) => setDraft({ ...draft, endTime: event.target.value })} /></Field><Field label="Grace minutes"><Input type="number" min="0" value={draft.graceMinutes} onChange={(event) => setDraft({ ...draft, graceMinutes: Number(event.target.value) })} /></Field><Field label="Status"><select className={selectClass} value={draft.status} onChange={(event) => setDraft({ ...draft, status: event.target.value as ShiftGroupDraft['status'] })}>{['Active', 'Draft', 'Inactive'].map((status) => <option key={status}>{status}</option>)}</select></Field><Field label="Working days" className="sm:col-span-2"><WorkingDaysPicker value={draft.workingDays} onChange={(workingDays) => setDraft({ ...draft, workingDays })} /></Field><CheckRow label="Overtime eligible" checked={draft.overtimeEligible} onChange={(overtimeEligible) => setDraft({ ...draft, overtimeEligible })} /><div className="flex justify-end sm:col-span-2"><Button type="submit">Add shift group</Button></div></form>;
};

const CheckRow: React.FC<{ label: string; checked: boolean; onChange: (checked: boolean) => void }> = ({ label, checked, onChange }) => <Label className="flex items-center gap-2 rounded-sm border border-slate-200 bg-slate-50 px-3 py-2 text-sm font-medium text-slate-700"><Checkbox checked={checked} onCheckedChange={(value) => onChange(Boolean(value))} />{label}</Label>;
